export enum PosButtonType {
  QtyUp = 'Qty Up',
  QtyDown = 'Qty Down',
  CashSale = 'Cash Sale',
  CardSale = 'Card Sale',
  Products = 'Products',
  Clear = 'Clear',
  Qty = 'Qty',
  Customers = 'Customers',
  ViewSales = 'View Sales',
  Price = 'Price',
  Hold = 'Hold',
  Medium = 'Medium',
  Remove = 'Remove',
  Recall = 'Recall',
  Large = 'Large',
  Discount = 'Discount',
  Purchase = 'Purchase',
  MoreOption = 'More Option',
  AddMessage = 'Add Message',
  Salesman = 'Salesman',
  FrequentItem = 'Frequent Item',
}
